hatch/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^browserid/', include('django_browserid.urls')),
    url(r'^inplaceeditform/', include('inplaceeditform.urls')),

    # Examples:
    # url(r'^$', 'hatch.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^list/', include('simplelist.urls', namespace='simplelist')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('simplelist.urls', namespace='simplelist')),
)

simplelist/urls.py
from django.conf.urls import patterns, url

from simplelist import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^list/(?P<list_id>\d+)/$', views.list_detail, name='list_detail'),
    #url(r'^entry/(?P<entry_id>\d+)/$', views.entry_detail, name='entry_detail'),
    url(r'^entry/(?P<pk>\d+)/$', views.EntryListView.as_view(), name='entry_detail'),
    #url(r'^entry/(?P<pk>\d+)/$', views.EntryDetailView.as_view(), name='entry_detail'),
)

simplelist/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User

import datetime
from django.utils import timezone

class List(models.Model):
    list_name = models.CharField(max_length=200)
    create_date = models.DateTimeField('date created')
    created_by = models.ForeignKey(User)
    # This function is maintained only as a template for later functions
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.list_name

class Entry(models.Model):
    MAX_SHORT_TEXT_LENGTH = 55;

    ## TODO - rename each of the following to its 'verbose' name
    sort = models.IntegerField(default=0, null=False)
    concept = models.CharField(max_length=200, blank=True)
    description = models.CharField(max_length=2000, blank=True)
    create_date = models.DateTimeField('date created')
    creator = models.ForeignKey(User)
    list = models.ForeignKey(List)
    def short_text(self):
        if len(self.concept):
            return "H: "+self.concept[0:Entry.MAX_SHORT_TEXT_LENGTH];
        else:
            return "B: "+self.description[0:Entry.MAX_SHORT_TEXT_LENGTH];

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.short_text();


## TODO: move this to a tables.py

# # Attempting to follow http://django-tables2.readthedocs.org/en/latest/
# import django_tables2 as tables
# from django_tables2.utils import A  # alias for Accessor
# class EntryTable(tables.Table):
#     name = tables.LinkColumn('simplelist.entry_detail', args=[A('pk')])
#     class Meta:
#         model = Entry
#         #exclude = ('id',)
#         attrs = {"class": "paleblue"}

# Attempting to follow http://stackoverflow.com/a/11931849/527489
import django_tables2 as tables
class EntryTable(tables.Table):
    concept_link = tables.TemplateColumn(template_name='simplelist/entry_detail_concept_editinplace.html')
    description = tables.TemplateColumn(template_name='simplelist/entry_detail_description_editinplace.html')
    # View = tables.TemplateColumn(verbose_name=_('Details'),
    #                              template_name='simplelist/entry_detail_link.html',
    #                              sortable=False)
    class Meta:
        model = Entry
        exclude = ('id','list','concept','creator')
        attrs = {'class': 'paleblue'}
        sequence = ('sort', 
                    'concept_link',
                    'description',
                    'create_date',
                    )

simplelist/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.views import generic


from simplelist.models import List, Entry, EntryTable

class IndexView(generic.ListView):
    template_name = 'simplelist/index.html'
#    model = List
    context_object_name = 'list_of_lists'

    def get_queryset(self):
        """Return the lists."""
        return List.objects.order_by('create_date')[:]


# Note: There's also a get_list_or_404() function, which works just as
# get_object_or_404() – except using filter() instead of get(). It 
# raises Http404 if the list is empty.
def list_detail(request, list_id):
    list = get_object_or_404(List, pk=list_id)
    entry_list = list.entry_set.all()
    table = EntryTable(entry_list)
    return render(request, "simplelist/list_detail.html", {"list_name": list.list_name, "table": table})
    #template_name = 'simplelist/list_detail.html'

class EntryDetailView(generic.DetailView):
    model = Entry
    template_name = 'simplelist/entry_detail.html'

simplelist/templates/simplelist/base.html
<!DOCTYPE html>
{% load browserid %}
{% load inplace_edit %}
{% load staticfiles %}
<html lang="en">
<head>
  <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
  {% inplace_toolbar %}
  <link rel="stylesheet" type="text/css" href="{% static 'simplelist/style.css' %}" />
  {% browserid_css %}
  {% block custom_head_content %}    {% endblock %}
  <title>{% block title %}amazing simplelist{% endblock %}</title>
</head>
<body>
    <div id="sidebar">
      {% browserid_info %}
      {% block sidebar %}
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/admin/">Admin</a></li>
        <li>
          {% if not user.is_authenticated %}
             {% browserid_login text='Login' color='dark' %} <h2> WARNING: Persona login seems broken - use admin</h2>
          {% else %}
             {% browserid_logout text='Logout' %}
          {% endif %}
        </li>

      </ul>
      {% endblock %}
    </div>

    <div id="content">
        {% if not user.is_authenticated %}
            {% block content_not_logged_in %}
               <p>You are not logged in.</p>
           {% endblock %}
        {% else %}
           {% block content_logged_in %}
               <h2>view template has not defined block: content_logged_in</h2>
           {% endblock %}
      {% endif %}
    </div>

   {% browserid_js %}
   {% inplace_js 1 1 %}
    </body>
</html>

simplelist/templates/simplelist/detail.html
{% extends "simplelist/base.html" %}

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'simplelist/style.css' %}" />

  {% block custom_head_content %}  
        <link rel="stylesheet" href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css" />
        {% load render_table from django_tables2 %}
  {% endblock %}

{% block title %}  List detail view   {% endblock %}

{% block content_logged_in %}
   <h1>{{ list_name }}</h1>
   {% render_table table %}
{% endblock %}

simplelist/templates/simplelist/entry_detail.html
{% extends "simplelist/base.html" %}
{% load inplace_edit %}

{% load staticfiles %}
  {% block custom_head_content %} 
<link rel="stylesheet" type="text/css" href="{% static 'simplelist/style.css' %}" />
   {% endblock %}

{% block title %}  {{ entry.concept }}  {% endblock %}

{% block content_logged_in %}
<h2> {% inplace_edit  "entry.concept" %} </h2>
<p> {% inplace_edit  "entry.description" %} </p>
{% endblock %}

simplelist/templates/simplelist/entry_detail_concept_editinplace.html
{% load inplace_edit %}

<a href="{% url 'simplelist:entry_detail' record.pk %}">{% inplace_edit "record.concept" %}</a>

simplelist/templates/simplelist/index.html
{% extends "simplelist/base.html" %}
{% load inplace_edit %}

{% block title %}Hatch - think outside the shell{% endblock %}

{% block content_logged_in %}
   <article>
     {% if list_of_lists %}
         <h1>List of lists</h1>
         <ul>
           {% for list in list_of_lists %}
           <li><a href="{% url 'simplelist:list_detail' list.id %}"> {% inplace_edit "list.list_name" %} </a></li>
           {% endfor %}
         </ul>
      {% else %}
           <p> There seem not to be any lists </p>
      {% endif %}
   </article>
{% endblock %}

simplelist/templates/simplelist/list_detail.html
{% extends "simplelist/base.html" %}

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'simplelist/style.css' %}" />

  {% block custom_head_content %}  
        <link rel="stylesheet" href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css" />
        {% load render_table from django_tables2 %}
  {% endblock %}

{% block title %}  List detail view   {% endblock %}

{% block content_logged_in %}
   <h1>{{ list_name }}</h1>
   {% render_table table %}
{% endblock %}